name: Release

on:
  push:
    branches: ["1.x", "main", "beta"]
  pull_request:
    branches: ["1.x", "main", "beta"]

jobs:
  test:
    name: "🧪 Test: (Node: ${{ matrix.node-version }})"
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} with pnpm
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test:cov

  release:
    name: "Release"

    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/1.x' }}
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js with pnpm
        uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
